package com.jmeterwebinsightreport.report.exporter;

import com.jmeterwebinsightreport.core.model.ReportData;
import com.jmeterwebinsightreport.core.parser.JtlParser;
import com.jmeterwebinsightreport.report.generator.ReportConfiguration;
import com.jmeterwebinsightreport.report.generator.WebInsightReportGenerator;
import org.apache.jmeter.report.config.ReportGeneratorConfiguration;
import org.apache.jmeter.report.dashboard.AbstractDataExporter;
import org.apache.jmeter.report.dashboard.ExportException;
import org.apache.jmeter.report.processor.SampleContext;
import org.apache.jmeter.util.JMeterUtils;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import java.io.File;

/**
 * JMeter Data Exporter for the -g -o report generation pipeline.
 * <p>
 * Registered via {@code jmeter.reportgenerator.exporter.webinsight.class_name} in jmeter.properties.
 * When the user runs {@code jmeter -g results.jtl -o report/}, JMeter's ReportGenerator
 * calls this exporter. We re-parse the JTL file with our own JtlParser to produce a
 * full-fidelity ReportData, then generate the HTML report.
 * </p>
 * <p>
 * Note: The {@code file} parameter in {@link #export} is the <b>source JTL file</b>,
 * not the output directory. The output directory is read from the exporter property
 * {@code output_dir} or from JMeter property {@code jmeter.reportgenerator.outputdir}.
 * </p>
 */
public class WebInsightDataExporter extends AbstractDataExporter {

    private static final Logger log = LoggerFactory.getLogger(WebInsightDataExporter.class);

    private static final String PROP_OUTPUT_DIR = "output_dir";
    private static final String PROP_OUTPUT_DIR_DEFAULT = "report-output";

    public WebInsightDataExporter() {
        super();
    }

    @Override
    public void setName(String name) {
        super.setName(name);
    }

    @Override
    public void export(SampleContext context, File jtlFile,
                       ReportGeneratorConfiguration reportGeneratorConfiguration)
            throws ExportException {
        log.info("Web Insight Data Exporter: starting report generation from JTL: {}", jtlFile);

        try {
            // 1. Resolve output directory from exporter properties or JMeter properties
            File outputDir = resolveOutputDirectory(reportGeneratorConfiguration);

            // 2. Check for collision — if listener already generated a report, skip
            File existingJson = new File(outputDir, "web-insight-report.json");
            if (existingJson.exists()) {
                log.info("Web Insight report already exists in {} (likely generated by listener). Skipping CLI generation.", outputDir);
                return;
            }

            // 3. Read configuration from JMeter properties (-J flags)
            ReportConfiguration config = buildConfiguration(outputDir);

            // 4. Parse the JTL file with our parser
            JtlParser parser = new JtlParser();
            if (config.getRampUpDurationMillis() > 0) {
                parser.setRampUpDurationMillis(config.getRampUpDurationMillis());
            }

            // Apdex threshold from -J property
            String apdexStr = JMeterUtils.getProperty("webinsight.apdex.threshold");
            if (apdexStr != null && !apdexStr.isEmpty()) {
                try {
                    parser.setApdexThreshold(Double.parseDouble(apdexStr));
                } catch (NumberFormatException e) {
                    log.warn("Invalid webinsight.apdex.threshold: {}", apdexStr);
                }
            }

            String testName = config.getReportTitle();
            ReportData reportData = parser.parse(jtlFile, testName);

            // 5. Set JMeter version in metadata
            try {
                String version = JMeterUtils.getJMeterVersion();
                if (version != null) {
                    reportData.getMetadata().setJmeterVersion(version);
                }
            } catch (Exception e) {
                // JMeterUtils may not be available
            }

            // 6. Auto-detect annotations and baseline in output directory
            autoDetectCompanionFiles(config, outputDir);

            // 7. Generate the report
            WebInsightReportGenerator generator = new WebInsightReportGenerator(config);
            File reportFile = generator.generateReport(reportData);

            log.info("Web Insight Report generated: {}", reportFile.getAbsolutePath());
            System.out.println("Web Insight Report generated: " + reportFile.getAbsolutePath());

        } catch (ExportException e) {
            throw e;
        } catch (Exception e) {
            throw new ExportException("Failed to generate Web Insight Report from JTL: " + jtlFile, e);
        }
    }

    /**
     * Resolve the output directory.
     * Priority: (1) -o CLI flag via jmeter.reportgenerator.outputdir property,
     * (2) exporter-specific output_dir property, (3) default report-output.
     */
    private File resolveOutputDirectory(ReportGeneratorConfiguration config) throws ExportException {
        // 1. Check JMeter property set by -o flag (highest priority)
        String jmeterOutputDir = JMeterUtils.getProperty("jmeter.reportgenerator.outputdir");
        if (jmeterOutputDir != null && !jmeterOutputDir.isEmpty()) {
            return new File(jmeterOutputDir);
        }

        // 2. Get this exporter's own output_dir property from reportgenerator.properties
        if (config.getExportConfigurations() != null && config.getExportConfigurations().containsKey(getName())) {
            try {
                File defaultDir = new File(JMeterUtils.getJMeterBinDir(), PROP_OUTPUT_DIR_DEFAULT);
                File dir = getPropertyFromConfig(
                        config.getExportConfigurations().get(getName()),
                        PROP_OUTPUT_DIR, defaultDir, File.class);
                if (dir != null) return dir;
            } catch (Exception e) {
                log.debug("Could not read output_dir from exporter config: {}", e.getMessage());
            }
        }

        // 3. Default
        return new File(JMeterUtils.getJMeterBinDir(), PROP_OUTPUT_DIR_DEFAULT);
    }

    /**
     * Build ReportConfiguration from JMeter -J properties.
     */
    private ReportConfiguration buildConfiguration(File outputDir) {
        ReportConfiguration config = new ReportConfiguration();
        config.setOutputDirectory(outputDir);

        String title = JMeterUtils.getProperty("webinsight.report.title");
        if (title != null && !title.isEmpty()) {
            config.setReportTitle(title);
        }

        String filename = JMeterUtils.getProperty("webinsight.report.filename");
        if (filename != null && !filename.isEmpty()) {
            config.setReportFilename(filename);
        }

        String baseline = JMeterUtils.getProperty("webinsight.report.baseline");
        if (baseline != null && !baseline.isEmpty()) {
            config.setBaselineJtlFile(new File(baseline));
        }

        String annotations = JMeterUtils.getProperty("webinsight.report.annotations");
        if (annotations != null && !annotations.isEmpty()) {
            config.setAnnotationsFile(new File(annotations));
        }

        String rampUp = JMeterUtils.getProperty("webinsight.report.rampup");
        if (rampUp != null && !rampUp.isEmpty()) {
            try {
                config.setRampUpDurationMillis(Long.parseLong(rampUp));
            } catch (NumberFormatException e) {
                log.warn("Invalid rampup value: {}", rampUp);
            }
        }

        String junitProp = JMeterUtils.getProperty("webinsight.report.junit");
        if ("true".equalsIgnoreCase(junitProp)) {
            config.setGenerateJunitXml(true);
        }

        return config;
    }

    /**
     * Auto-detect report-annotations.json and baseline.jtl in the output directory.
     */
    private void autoDetectCompanionFiles(ReportConfiguration config, File outputDir) {
        if (config.getAnnotationsFile() == null) {
            File autoAnnotations = new File(outputDir, "report-annotations.json");
            if (autoAnnotations.exists()) {
                config.setAnnotationsFile(autoAnnotations);
                log.info("Auto-detected annotations file: {}", autoAnnotations.getAbsolutePath());
            }
        }

        if (config.getBaselineJtlFile() == null) {
            File autoBaseline = new File(outputDir, "baseline.jtl");
            if (autoBaseline.exists()) {
                config.setBaselineJtlFile(autoBaseline);
                log.info("Auto-detected baseline JTL: {}", autoBaseline.getAbsolutePath());
            }
        }
    }
}
